Fix generator test, still fails the smoke test
Fixing the parse error does not allow deployment as another error occurs:

```
thread 'smoke::smoke_test_path_require' panicked at /Users/rschneeman/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libcnb-test-0.28.1/src/test_runner.rs:163:17:
Error performing pack build:

pack command failed with exit code 1!

## stderr:

No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
Loading composer repositories with package information
Updating dependencies
Lock file operations: 27 installs, 0 updates, 0 removals
  - Locking fig/http-message-util (1.1.5)
  - Locking heroku-sys/composer (2.8.2)
  - Locking heroku-sys/php (8.3.13)
  - Locking heroku/installer-plugin (1.8.0)
  - Locking laravel/serializable-closure (v1.3.7)
  - Locking monolog/monolog (3.8.0)
  - Locking nikic/fast-route (v1.3.0)
  - Locking php-di/invoker (2.3.4)
  - Locking php-di/php-di (7.0.7)
  - Locking php-di/slim-bridge (3.4.1)
  - Locking psr/clock (dev-master)
  - Locking psr/container (2.0.2)
  - Locking psr/http-factory (1.1.0)
  - Locking psr/http-message (2.0)
  - Locking psr/http-server-handler (1.0.2)
  - Locking psr/http-server-middleware (1.0.2)
  - Locking psr/log (3.0.2)
  - Locking ralouphie/getallheaders (3.0.3)
  - Locking slim/psr7 (1.7.0)
  - Locking slim/slim (4.14.0)
  - Locking slim/twig-view (3.4.1)
  - Locking symfony/deprecation-contracts (v3.5.1)
  - Locking symfony/polyfill-ctype (v1.31.0)
  - Locking symfony/polyfill-mbstring (v1.31.0)
  - Locking symfony/polyfill-php80 (v1.31.0)
  - Locking symfony/polyfill-php81 (v1.31.0)
  - Locking twig/twig (v3.16.0)
Writing lock file
Installing dependencies from lock file
Package operations: 27 installs, 0 updates, 0 removals
  - Installing heroku/installer-plugin (1.8.0): Mirroring from /layers/heroku_php/bootstrap_installer/support/installer
  - Downloading heroku-sys/php (8.3.13)
  - Downloading heroku-sys/composer (2.8.2)
 0/2 [>---------------------------]   0%
 1/2 [==============>-------------]  50%
 2/2 [============================] 100%
  - Installing heroku-sys/php (8.3.13)
  - Installing fig/http-message-util (1.1.5)
  - Installing heroku-sys/composer (2.8.2)
  - Installing laravel/serializable-closure (v1.3.7)
  - Installing monolog/monolog (3.8.0)
  - Installing nikic/fast-route (v1.3.0)
  - Installing php-di/invoker (2.3.4)
  - Installing php-di/php-di (7.0.7)
  - Installing php-di/slim-bridge (3.4.1)
  - Installing psr/clock (dev-master)
  - Installing psr/container (2.0.2)
  - Installing psr/http-factory (1.1.0)
  - Installing psr/http-message (2.0)
  - Installing psr/http-server-handler (1.0.2)
  - Installing psr/http-server-middleware (1.0.2)
  - Installing psr/log (3.0.2)
  - Installing ralouphie/getallheaders (3.0.3)
  - Installing slim/psr7 (1.7.0)
  - Installing slim/slim (4.14.0)
  - Installing slim/twig-view (3.4.1)
  - Installing symfony/deprecation-contracts (v3.5.1)
  - Installing symfony/polyfill-ctype (v1.31.0)
  - Installing symfony/polyfill-mbstring (v1.31.0)
  - Installing symfony/polyfill-php80 (v1.31.0)
  - Installing symfony/polyfill-php81 (v1.31.0)
  - Installing twig/twig (v3.16.0)
    0 [>---------------------------]    0 [->--------------------------]
Generating autoload files
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
Loading composer repositories with package information
Updating dependencies
Lock file operations: 4 installs, 0 updates, 0 removals
  - Locking heroku-sys/apache (2.4.62)
  - Locking heroku-sys/nginx (1.26.2)
  - Locking heroku/heroku-buildpack-php (dev-bundled)
  - Locking heroku/installer-plugin (1.8.0)
Writing lock file
Installing dependencies from lock file
Package operations: 4 installs, 0 updates, 0 removals
  - Installing heroku/installer-plugin (1.8.0): Mirroring from /layers/heroku_php/bootstrap_installer/support/installer
  - Downloading heroku-sys/apache (2.4.62)
  - Downloading heroku-sys/nginx (1.26.2)
 0/2 [>---------------------------]   0%
 2/2 [============================] 100%
  - Installing heroku-sys/apache (2.4.62)
  - Installing heroku-sys/nginx (1.26.2)
  - Installing heroku/heroku-buildpack-php (dev-bundled): Mirroring from /layers/heroku_php/bootstrap_installer
    0 [>---------------------------]    0 [->--------------------------]
Generating autoload files
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Dependency resolution completed in 0.000 seconds
Package operations: 24 installs, 0 updates, 0 removals
Installs: laravel/serializable-closure:v1.3.7, psr/log:3.0.2, monolog/monolog:3.8.0, nikic/fast-route:v1.3.0, psr/http-message:2.0, psr/http-server-handler:1.0.2, psr/http-server-middleware:1.0.2, psr/http-factory:1.1.0, psr/container:2.0.2, slim/slim:4.14.0, php-di/invoker:2.3.4, php-di/php-di:7.0.7, php-di/slim-bridge:3.4.1, psr/clock:dev-master fb246b4, symfony/polyfill-php80:v1.31.0, ralouphie/getallheaders:3.0.3, fig/http-message-util:1.1.5, slim/psr7:1.7.0, symfony/polyfill-php81:v1.31.0, symfony/polyfill-mbstring:v1.31.0, symfony/polyfill-ctype:v1.31.0, symfony/deprecation-contracts:v3.5.1, twig/twig:v3.16.0, slim/twig-view:3.4.1
  - Downloading laravel/serializable-closure (v1.3.7)
  - Downloading psr/log (3.0.2)
  - Downloading monolog/monolog (3.8.0)
  - Downloading nikic/fast-route (v1.3.0)
  - Downloading psr/http-message (2.0)
  - Downloading psr/http-server-handler (1.0.2)
  - Downloading psr/http-server-middleware (1.0.2)
  - Downloading psr/http-factory (1.1.0)
  - Downloading psr/container (2.0.2)
  - Downloading slim/slim (4.14.0)
  - Downloading php-di/invoker (2.3.4)
  - Downloading php-di/php-di (7.0.7)
  - Downloading php-di/slim-bridge (3.4.1)
  - Downloading symfony/polyfill-php80 (v1.31.0)
  - Downloading ralouphie/getallheaders (3.0.3)
  - Downloading fig/http-message-util (1.1.5)
  - Downloading slim/psr7 (1.7.0)
  - Downloading symfony/polyfill-php81 (v1.31.0)
  - Downloading symfony/polyfill-mbstring (v1.31.0)
  - Downloading symfony/polyfill-ctype (v1.31.0)
  - Downloading symfony/deprecation-contracts (v3.5.1)
  - Downloading twig/twig (v3.16.0)
  - Downloading slim/twig-view (3.4.1)
  - Installing laravel/serializable-closure (v1.3.7): Extracting archive
  - Installing psr/log (3.0.2): Extracting archive
  - Installing monolog/monolog (3.8.0): Extracting archive
  - Installing nikic/fast-route (v1.3.0): Extracting archive
  - Installing psr/http-message (2.0): Extracting archive
  - Installing psr/http-server-handler (1.0.2): Extracting archive
  - Installing psr/http-server-middleware (1.0.2): Extracting archive
  - Installing psr/http-factory (1.1.0): Extracting archive
  - Installing psr/container (2.0.2): Extracting archive
  - Installing slim/slim (4.14.0): Extracting archive
  - Installing php-di/invoker (2.3.4): Extracting archive
  - Installing php-di/php-di (7.0.7): Extracting archive
  - Installing php-di/slim-bridge (3.4.1): Extracting archive
  - Installing psr/clock (dev-master fb246b4): Cloning fb246b49699693265d21cb078d9173db28658665
    Install of psr/clock failed
  - Installing symfony/polyfill-php80 (v1.31.0): Extracting archive
  - Installing ralouphie/getallheaders (3.0.3): Extracting archive
  - Installing fig/http-message-util (1.1.5): Extracting archive
  - Installing slim/psr7 (1.7.0): Extracting archive
  - Installing symfony/polyfill-php81 (v1.31.0): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.31.0): Extracting archive
  - Installing symfony/polyfill-ctype (v1.31.0): Extracting archive
  - Installing symfony/deprecation-contracts (v3.5.1): Extracting archive
  - Installing twig/twig (v3.16.0): Extracting archive
  - Installing slim/twig-view (3.4.1): Extracting archive

In Git.php line 520:

  [RuntimeException]
  Failed to execute git clone --no-checkout -- '/workspace/clock' '/workspace
  /vendor/psr/clock' && cd '/workspace/vendor/psr/clock' && git remote add co
  mposer -- '/workspace/clock' && git fetch composer && git remote set-url or
  igin -- '/workspace/clock' && git remote set-url composer -- '/workspace/cl
  ock'

  fatal: repository '/workspace/clock' does not exist


Exception trace:
  at phar:///layers/heroku_php/platform/bin/composer/src/Composer/Util/Git.php:520
 Composer\Util\Git->throwException() at phar:///layers/heroku_php/platform/bin/composer/src/Composer/Util/Git.php:305
 Composer\Util\Git->runCommand() at phar:///layers/heroku_php/platform/bin/composer/src/Composer/Downloader/GitDownloader.php:135
 Composer\Downloader\GitDownloader->doInstall() at phar:///layers/heroku_php/platform/bin/composer/src/Composer/Downloader/VcsDownloader.php:137
 Composer\Downloader\VcsDownloader->install() at phar:///layers/heroku_php/platform/bin/composer/src/Composer/Downloader/DownloadManager.php:273
 Composer\Downloader\DownloadManager->install() at phar:///layers/heroku_php/platform/bin/composer/src/Composer/Installer/LibraryInstaller.php:281
 Composer\Installer\LibraryInstaller->installCode() at phar:///layers/heroku_php/platform/bin/composer/src/Composer/Installer/LibraryInstaller.php:152
 Composer\Installer\LibraryInstaller->install() at phar:///layers/heroku_php/platform/bin/composer/src/Composer/Installer/InstallationManager.php:467
 Composer\Installer\InstallationManager->install() at phar:///layers/heroku_php/platform/bin/composer/src/Composer/Installer/InstallationManager.php:381
 Composer\Installer\InstallationManager->Composer\Installer\{closure}() at phar:///layers/heroku_php/platform/bin/composer/vendor/react/promise/src/Internal/FulfilledPromise.php:47
 React\Promise\Internal\FulfilledPromise->then() at phar:///layers/heroku_php/platform/bin/composer/src/Composer/Installer/InstallationManager.php:380
 Composer\Installer\InstallationManager->executeBatch() at phar:///layers/heroku_php/platform/bin/composer/src/Composer/Installer/InstallationManager.php:322
 Composer\Installer\InstallationManager->downloadAndExecuteBatch() at phar:///layers/heroku_php/platform/bin/composer/src/Composer/Installer/InstallationManager.php:221
 Composer\Installer\InstallationManager->execute() at phar:///layers/heroku_php/platform/bin/composer/src/Composer/Installer.php:839
 Composer\Installer->doInstall() at phar:///layers/heroku_php/platform/bin/composer/src/Composer/Installer.php:300
 Composer\Installer->run() at phar:///layers/heroku_php/platform/bin/composer/src/Composer/Command/InstallCommand.php:147
 Composer\Command\InstallCommand->execute() at phar:///layers/heroku_php/platform/bin/composer/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar:///layers/heroku_php/platform/bin/composer/vendor/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at phar:///layers/heroku_php/platform/bin/composer/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at phar:///layers/heroku_php/platform/bin/composer/src/Composer/Console/Application.php:396
 Composer\Console\Application->doRun() at phar:///layers/heroku_php/platform/bin/composer/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar:///layers/heroku_php/platform/bin/composer/src/Composer/Console/Application.php:136
 Composer\Console\Application->run() at phar:///layers/heroku_php/platform/bin/composer/bin/composer:93
 require() at /layers/heroku_php/platform/bin/composer:29

install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--download-only] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [--audit] [--audit-format AUDIT-FORMAT] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]


[Error: Failed to install dependencies]
Dependency installation failed!

The 'composer install' process failed with an error. The cause
may be the download or installation of packages, or a pre- or
post-install hook (e.g. a 'post-install-cmd' item in 'scripts')
in your 'composer.json'.

Typical error cases are out-of-date or missing parts of code,
timeouts when making external connections, or memory limits.

Check the above error output closely to determine the cause of
the problem, ensure the code you're pushing is functioning
properly, and that all local changes are committed correctly.

For more information on builds for PHP on Heroku, refer to
https://devcenter.heroku.com/articles/php-support
ERROR: failed to build: executing lifecycle: failed with status code: 51

## stdout:

Warning: Exporting to docker daemon (building without --publish) and daemon uses containerd storage; performance may be significantly degraded.
For more information, see https://github.com/buildpacks/pack/issues/2272.
===> ANALYZING
Image with name "libcnbtest_xbyxtqvnefoy" not found
===> DETECTING
heroku/php 0.2.3
===> RESTORING
===> BUILDING

[Bootstrapping]

[Preparing platform packages installation]

[Installing platform packages]

[Installing web servers]

[Installing dependencies]
ERROR: failed to build: exit status 1


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test smoke::smoke_test_path_require ... FAILED

failures:

failures:
    smoke::smoke_test_path_require

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 3 filtered out; finished in 34.07s

error: test failed, to rerun pass `-p php-buildpack --test integration`
cargo test -- --ignored --test smoke_test_path_require --nocapture  17.98s user 5.06s system 67% cpu 34.302 total
```


The same failure occurs on classic:

```
$ git co schneems/reproduction-buildpacks-php-issue-105
Already on 'schneems/reproduction-buildpacks-php-issue-105'
Your branch is up to date with 'origin/schneems/reproduction-buildpacks-php-issue-105'.
$ empty
[schneems/reproduction-buildpacks-php-issue-105 c65d3ae] empty
$ git pushf heroku schneems/reproduction-buildpacks-php-issue-105:main
Enumerating objects: 17, done.
Counting objects: 100% (17/17), done.
Delta compression using up to 12 threads
Compressing objects: 100% (9/9), done.
Writing objects: 100% (14/14), 4.18 KiB | 4.18 MiB/s, done.
Total 14 (delta 4), reused 13 (delta 3), pack-reused 0 (from 0)
remote: Updated 24 paths from 854cd1b
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Building on the Heroku-24 stack
remote: -----> Using buildpack: heroku/php
remote: -----> PHP app detected
remote: -----> Bootstrapping...
remote: -----> Preparing platform package installation...
remote: -----> Installing platform packages...
remote:        - php (8.4.5)
remote:        - apache (2.4.63)
remote:        - composer (2.8.6)
remote:        - nginx (1.26.3)
remote: -----> Installing dependencies...
remote:        Composer version 2.8.6 2025-02-25 13:03:50
remote:        Installing dependencies from lock file
remote:        Verifying lock file contents can be installed on current platform.
remote:        Package operations: 24 installs, 0 updates, 0 removals
remote:          - Installing laravel/serializable-closure (v1.3.7): Extracting archive
remote:          - Installing psr/log (3.0.2): Extracting archive
remote:          - Installing monolog/monolog (3.8.0): Extracting archive
remote:          - Installing nikic/fast-route (v1.3.0): Extracting archive
remote:          - Installing psr/http-message (2.0): Extracting archive
remote:          - Installing psr/http-server-handler (1.0.2): Extracting archive
remote:          - Installing psr/http-server-middleware (1.0.2): Extracting archive
remote:          - Installing psr/http-factory (1.1.0): Extracting archive
remote:          - Installing psr/container (2.0.2): Extracting archive
remote:          - Installing slim/slim (4.14.0): Extracting archive
remote:          - Installing php-di/invoker (2.3.4): Extracting archive
remote:          - Installing php-di/php-di (7.0.7): Extracting archive
remote:          - Installing php-di/slim-bridge (3.4.1): Extracting archive
remote:          - Installing psr/clock (dev-master fb246b4): Cloning fb246b4969
remote:            Install of psr/clock failed
remote:          - Installing symfony/polyfill-php80 (v1.31.0): Extracting archive
remote:          - Installing ralouphie/getallheaders (3.0.3): Extracting archive
remote:          - Installing fig/http-message-util (1.1.5): Extracting archive
remote:          - Installing slim/psr7 (1.7.0): Extracting archive
remote:          - Installing symfony/polyfill-php81 (v1.31.0): Extracting archive
remote:          - Installing symfony/polyfill-mbstring (v1.31.0): Extracting archive
remote:          - Installing symfony/polyfill-ctype (v1.31.0): Extracting archive
remote:          - Installing symfony/deprecation-contracts (v3.5.1): Extracting archive
remote:          - Installing twig/twig (v3.16.0): Extracting archive
remote:          - Installing slim/twig-view (3.4.1): Extracting archive
remote:
remote:        In Git.php line 587:
remote:
remote:          Failed to execute git clone --no-checkout -- /tmp/build_3b844ead/clock /tmp
remote:          /build_3b844ead/vendor/psr/clock
remote:
remote:          fatal: repository '/tmp/build_3b844ead/clock' does not exist
remote:
remote:
remote:        install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--download-only] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [--audit] [--audit-format AUDIT-FORMAT] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]
remote:
remote:
remote:  !     ERROR: Dependency installation failed!
remote:  !
remote:  !     The 'composer install' process failed with an error. The cause
remote:  !     may be the download or installation of packages, or a pre- or
remote:  !     post-install hook (e.g. a 'post-install-cmd' item in 'scripts')
remote:  !     in your 'composer.json'.
remote:  !
remote:  !     Typical error cases are out-of-date or missing parts of code,
remote:  !     timeouts when making external connections, or memory limits.
remote:  !
remote:  !     Check the above error output closely to determine the cause of
remote:  !     the problem, ensure the code you're pushing is functioning
remote:  !     properly, and that all local changes are committed correctly.
remote:  !
remote:  !     For more information on builds for PHP on Heroku, refer to
remote:  !     https://devcenter.heroku.com/articles/php-support
remote:
remote:  !     Push rejected, failed to compile PHP app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !	Push rejected to secret-meadow-86727.
remote:
To https://git.heroku.com/secret-meadow-86727.git
 ! [remote rejected] schneems/reproduction-buildpacks-php-issue-105 -> main (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/secret-meadow-86727.git'
```