Failing smoke test
```

thread 'smoke::smoke_test_path_require' panicked at /Users/rschneeman/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libcnb-test-0.28.1/src/test_runner.rs:163:17:
Error performing pack build:

pack command failed with exit code 1!

## stderr:


[Error: Failed to parse 'composer.lock']
There was an error parsing the lock file; it must be a valid
file generated by Composer and be in an up-to-date state.

Check below for any parse errors and address them if necessary.

The parsed contents were invalid.

Details: relative URL without a base: "./clock" at line 489 column 9

You most likely created or edited the file by hand, or a merge
conflict was not resolved properly, resulting in a syntax error
in the file. Refer to the docs for information on re-generating
the lock file: https://getcomposer.org/doc/01-basic-usage.md

Please perform the following steps locally on your computer to
resolve this issue before attempting another deploy:
1) Run 'composer update' to re-generate the lock file
2) stage the lock file changes using 'git add'
3) commit the change using 'git commit'

You can run 'composer validate' locally on your computer for
further diagnosis. Remember to also always keep your lock file
up to date with any changes according to the instructions at
https://getcomposer.org/doc/01-basic-usage.md

If you believe this message to be in error, please report it.
ERROR: failed to build: executing lifecycle: failed with status code: 51

## stdout:

Warning: Exporting to docker daemon (building without --publish) and daemon uses containerd storage; performance may be significantly degraded.
For more information, see https://github.com/buildpacks/pack/issues/2272.
===> ANALYZING
Image with name "libcnbtest_euwwwucigunh" not found
===> DETECTING
heroku/php 0.2.3
===> RESTORING
===> BUILDING
ERROR: failed to build: exit status 1


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test smoke::smoke_test_path_require ... FAILED

failures:

failures:
    smoke::smoke_test_path_require

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 3 filtered out; finished in 27.05s

error: test failed, to rerun pass `-p php-buildpack --test integration`
cargo test -- --ignored --test smoke_test_path_require --nocapture  18.48s user 4.71s system 85% cpu 27.242 total
```