Add failing test for #105
Adding a "path" type of "repositories" causes the lock parser to fail because the "url" is actually a path and not a valid URL. This reproduces one failure mode seen in 105:

```
 thread 'tests::platform::generator::make_platform_json_with_fixtures' panicked at buildpacks/php/src/tests/platform/generator.rs:37:10:
 called `Result::unwrap()` on an `Err` value: Error("relative URL without a base: \"./clock\"", line: 490, column: 9)
```