Fix smoke test
Fails on main, passes on this branch

```
$ git co main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
$  time cargo test -- --ignored --test smoke_test_path_require --nocapture

    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.13s
     Running unittests src/lib.rs (target/debug/deps/composer-2ccbfed8a5960c70)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 3 filtered out; finished in 0.00s

     Running unittests src/main.rs (target/debug/deps/php_buildpack-bf9503a6993837c0)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s

     Running tests/integration/main.rs (target/debug/deps/integration-b1db1538f49669ee)

running 1 test
Cloning into '/var/folders/yr/yytf3z3n3q336f1tj2b2j0gw0000gn/T/.tmp64VlAd'...
remote: Enumerating objects: 253, done.
remote: Counting objects: 100% (253/253), done.
remote: Compressing objects: 100% (137/137), done.
remote: Total 253 (delta 97), reused 253 (delta 97), pack-reused 0 (from 0)
Receiving objects: 100% (253/253), 84.35 KiB | 1.92 MiB/s, done.
Resolving deltas: 100% (97/97), done.
   Compiling composer v0.0.0 (/Users/rschneeman/Documents/projects/work/tmp/buildpacks-php/composer)
   Compiling php-buildpack v0.0.0 (/Users/rschneeman/Documents/projects/work/tmp/buildpacks-php/buildpacks/php)
    Finished `dev` profile [unoptimized] target(s) in 2.40s

thread 'smoke::smoke_test_path_require' panicked at /Users/rschneeman/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libcnb-test-0.28.1/src/test_runner.rs:163:17:
Error performing pack build:

pack command failed with exit code 1!

## stderr:


[Error: Failed to parse 'composer.lock']
There was an error parsing the lock file; it must be a valid
file generated by Composer and be in an up-to-date state.

Check below for any parse errors and address them if necessary.

The parsed contents were invalid.

Details: relative URL without a base: "./clock" at line 490 column 9

You most likely created or edited the file by hand, or a merge
conflict was not resolved properly, resulting in a syntax error
in the file. Refer to the docs for information on re-generating
the lock file: https://getcomposer.org/doc/01-basic-usage.md

Please perform the following steps locally on your computer to
resolve this issue before attempting another deploy:
1) Run 'composer update' to re-generate the lock file
2) stage the lock file changes using 'git add'
3) commit the change using 'git commit'

You can run 'composer validate' locally on your computer for
further diagnosis. Remember to also always keep your lock file
up to date with any changes according to the instructions at
https://getcomposer.org/doc/01-basic-usage.md

If you believe this message to be in error, please report it.
ERROR: failed to build: executing lifecycle: failed with status code: 51

## stdout:

Warning: Exporting to docker daemon (building without --publish) and daemon uses containerd storage; performance may be significantly degraded.
For more information, see https://github.com/buildpacks/pack/issues/2272.
===> ANALYZING
Image with name "libcnbtest_pmvnxvgivcdj" not found
===> DETECTING
heroku/php 0.2.3
===> RESTORING
===> BUILDING
ERROR: failed to build: exit status 1


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test smoke::smoke_test_path_require ... FAILED

failures:

failures:
    smoke::smoke_test_path_require

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 3 filtered out; finished in 25.90s

error: test failed, to rerun pass `-p php-buildpack --test integration`
cargo test -- --ignored --test smoke_test_path_require --nocapture  18.66s user 4.92s system 90% cpu 26.109 total
⛄️ 3.4.2 🚀 /Users/rschneeman/Documents/projects/work/tmp/buildpacks-php (main)
$ git diff
diff --git a/buildpacks/php/tests/integration/smoke.rs b/buildpacks/php/tests/integration/smoke.rs
index 61c398c..71f35ed 100644
--- a/buildpacks/php/tests/integration/smoke.rs
+++ b/buildpacks/php/tests/integration/smoke.rs
@@ -21,6 +21,34 @@ fn smoke_test_bundled_hello_world_app() {
     );
 }

+#[test]
+#[ignore = "integration test"]
+fn smoke_test_path_require() {
+    let build_config = BuildConfig::new(builder(), "tests/fixtures/smoke/hello-world")
+        .buildpacks(vec![BuildpackReference::CurrentCrate])
+        .target_triple(target_triple(builder()))
+        .app_dir_preprocessor(|app_dir| {
+            fs::remove_dir_all(&app_dir).unwrap();
+            fs::create_dir_all(&app_dir).unwrap();
+            std::process::Command::new("git")
+                .arg("clone")
+                .arg("https://github.com/sharpstone/php_path_dependency")
+                .arg(&app_dir)
+                .spawn()
+                .and_then(|mut child| child.wait())
+                .map(|status| {
+                    if status.success() {
+                    } else {
+                        panic!("Command failed")
+                    }
+                })
+                .unwrap();
+        })
+        .to_owned();
+
+    TestRunner::default().build(&build_config, |_context| {});
+}
+
 #[test]
 #[ignore = "integration test"]
 fn smoke_test_composer_json_scripts_as_objects() {
```