Enhance finalizer test error with details
The `config.toml` is used to configure expected warnings or other behavior, but is not present in every test case. It wasn't immediately clear that the failure here could be fixed by adding an expected statement to the config.toml so I added that information.


Before:

```
thread 'tests::platform::generator::make_platform_json_with_fixtures' panicked at buildpacks/php/src/tests/platform/generator.rs:181:9:
assertion `left == right` failed: case git_at_url: mismatched finalizer notices (left = generated, right = expected)
  left: {"RuntimeRequirementInserted(\"php\", \"*\")"}
 right: {}
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

After:

```
 assertion `left == right` failed: case `git_at_url`: mismatched finalizer notices. Update the `git_at_url/config.toml` or fix the behavior. (left = generated, right = expected)
   left: {"RuntimeRequirementInserted(\"php\", \"*\")"}
  right: {}
```